### ISSUE TITLE
Notifications not working, Filters not working

### ISSUE THREAD

**Issue by Znuff** [fourbytes/pogomap#5]
Also getting:

```
2016-07-28 02:23:33,288 [        app] [  ERROR] Exception on /next_loc [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/heatmap/pogomap/app.py", line 130, in next_loc
    set_cover()
NameError: name 'set_cover' is not defined
```

**Comment by fourbytes** [comment]
Interesting, that exception should be fixed now, I'll have a look into the notifications and filters though.

**Comment by Znuff** [comment]
No, that broke it:

```
Traceback (most recent call last):
  File "./runserver.py", line 13, in <module>
    from pogomap.app import Pogom
  File "/opt/heatmap/pogomap/app.py", line 22, in <module>
    from .models import set_cover
ImportError: cannot import name 'set_cover'
```

**Comment by fourbytes** [comment]
Alright, should be all fixed now.
